# Generated by Django 5.0.6 on 2024-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
